/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package tools

import org.gradle.api.Plugin
import org.gradle.api.Project
import org.gradle.api.Task
import org.gradle.api.initialization.resolve.RepositoriesMode
import org.gradle.api.tasks.TaskExecutionException
import java.io.File
import java.net.URI


/**
 * A simple 'hello world' plugin.
 */

private const val TAG = "[EdfapayPlugin]"
class SoftPosToolsExtension(private val project:Project) {
    var partnerCode:String? = null
    var version:String? = null
    var mode:String? = null
    var dependency:String? = null
    private var partnerName:String? = null

    val currentTask:Task get() = project.tasks.getByName("edfapay")


    fun install(partnerCode:String?){

        val partnerCode_ = lookForPartnerCode(partnerCode ?: this.partnerCode) ?: throw TaskExecutionException(currentTask, Errors.invalidPartnerCodeToInstall)
        val mode = lookForSdkMode(mode)
        val version = lookForSdkVersion(version)

        this.partnerName = Helper.hexToPartnerCode(partnerCode_) ?: throw TaskExecutionException(currentTask, Errors.invalidPartnerCodeToInstall)
        if(!partnerName!!.startsWith("partner~")){
            throw TaskExecutionException(currentTask, Errors.invalidPartnerCodeToInstall)
        }

        partnerName = partnerName?.replace("partner~", "")

        when(dependency == null) {
            true -> {
                val depStr = "com.edfapay"
                version?.let {
                    println("Skipping `mode` as `version` number exists...")
                    println("Installing edfapay sdk with parameters: version:$it | partnerCode:$partnerCode_")
                    dependency = "$depStr:$partnerName:$it"
                } ?: mode?.let {
                    println("Installing edfapay sdk with parameters: mode:$it | partnerCode:$partnerCode_")
                    dependency = "$depStr:$partnerName:$it-SNAPSHOT"
                } ?: throw TaskExecutionException(currentTask, Errors.invalidSdkVersionOrModeToInstall)

            }
            false -> {
                println("⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯")
                println("Dependency override: $dependency")
                println(" - `Mode/Version` and `Partner Code` cannot be considered to create `dependency`")
            }
        }
        println("⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯")
        println("Partner:       ︳ $partnerName")
        println("Mode:          ︳ ${mode ?: "Skipped"}")
        println("SDK:           ︳ $dependency")
        println("⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯")

        dependency?.let {
//            project.dependencies.add("implementEdfapay", it)
            project.dependencies.add("implementation", it)
        } ?: throw TaskExecutionException(currentTask, Errors.dependencyIsNull)

    }

    private fun lookForPartnerCode(partnerCode:String?) : String?{
        return (project.findProperty("EDFAPAY_PARTNER"))?.let {
            println("Partner Code Found at Global or Project Gradle Properties '~/.gradle/gradle.properties | ./gradle.properties'")
            it as String?
        } ?: System.getenv().get("EDFAPAY_PARTNER")?.let {
            println("Partner Code Found at Environment Variable")
            it
        } ?: partnerCode?.let {
            println("Partner Code passed by Gradle Script to edfapay.softpos.install() or edfapay.softpos.partnerCode")
            it
        }
    }

    private fun lookForSdkMode(mode:String?) : String?{
        return (project.findProperty("EDFAPAY_SDK_MODE"))?.let {
            println("SDK Mode Found at Global or Project Gradle Properties '~/.gradle/gradle.properties | ./gradle.properties'")
            it as String?
        } ?: System.getenv().get("EDFAPAY_SDK_MODE")?.let {
            println("SDK Mode Found at Environment Variable")
            it
        } ?: mode?.let {
            println("SDK Mode passed by Gradle Script to edfapay.softpos.mode")
            it
        }
    }

    private fun lookForSdkVersion(version:String?) : String?{
        return (project.findProperty("EDFAPAY_SDK_VERSION"))?.let {
            project.gradle.gradleHomeDir?.absolutePath
            println("SDK Version Found at Global or Project Gradle Properties '~/.gradle/gradle.properties | ./gradle.properties'")
            it as String?
        } ?: System.getenv().get("EDFAPAY_SDK_VERSION")?.let {
            println("SDK Version Found at Environment Variable")
            it
        } ?: version?.let {
            println("SDK Version passed by Gradle Script to edfapay.softpos.version")
            it
        }
    }

    private fun configurePartner(){
        project.afterEvaluate {
            project.configurations.getByName("implementEdfapay").resolve().forEach { aarFile ->
                val depsAarName = "card-sdk-$mode-SNAPSHOT.aar"

                if (aarFile.name.endsWith(depsAarName)) {
//                    println("->> ${aarFile.absolutePath}")

                    // Define a temporary directory to extract the AAR contents
                    val fname = aarFile.name.replace(".aar", "")
                    val modifedFolder = File(aarFile.parentFile.absolutePath + "/$fname")
                    modifedFolder.mkdir()

                    // Extract the contents of the AAR aarFile

                    project.copy {
                        it.from(project.zipTree(aarFile))
                        it.into(modifedFolder)
                    }

                    // Move assets to root from partner~assets directory

                    val partnerAssets = File(modifedFolder, "assets/$partnerName")
                    project.copy {
                        it.from(project.fileTree(partnerAssets))
                        it.into(partnerAssets.parentFile)
                    }

                    // Remove partner assets directories
                    if(partnerAssets.parentFile.listFiles()?.isNotEmpty() == true){
                        partnerAssets.parentFile.listFiles()?.toList()?.forEach {
                            if(it.name.startsWith("partner~")){
                                println("File Delete ${it.deleteRecursively()}: ${it.absolutePath}")
                            }
                        }
                    }
                    Helper.zipFolder(modifedFolder.toPath(), aarFile.toPath())
                }
            }
        }
    }
}

class Build: Plugin<Project> {
    val MODULE="$TAG[build.gradle]"
    private var project: Project? = null
    val logger: (String) -> Unit = { msg -> project?.logger?.lifecycle(msg) }

    override fun apply(project: Project) {
        this.project = project
        project.tasks.register("edfapay") { task ->
            task.extensions.add("softpos", SoftPosToolsExtension(project))
        }

        println("$MODULE Begins")
        logger("$MODULE Project: ${project.rootProject.name} > ${project.name}")

        val repositoriesMode = project.gradle.rootProject
            .extensions.extraProperties
            .properties["repositoriesMode"] ?: "null, considered ${RepositoriesMode.PREFER_PROJECT.name} as default"

        logger("$MODULE RepositoriesMode:$repositoriesMode")
        if(repositoriesMode == RepositoriesMode.PREFER_SETTINGS.name
            || repositoriesMode == RepositoriesMode.FAIL_ON_PROJECT_REPOS.name){
            logger("$MODULE Ignore adding edfapay repository at project level build.gradle")
            logger("$MODULE   - It may already added at settings.gradle level")
            return
        }


        val task = project.tasks.getByName("edfapay")

        val username = project.findProperty("PARTNER_REPO_USERNAME") ?: throw TaskExecutionException(task, Errors.missingPartnerRepoUsername)
        val password = project.findProperty("PARTNER_REPO_PASSWORD") ?: throw TaskExecutionException(task, Errors.missingPartnerRepoUserPassword)

        println("$MODULE username:$username")
        println("$MODULE password:${maskPassword(password as String)}")
        /*
        /* Applying via bundled gradle script */
        logger("$MODULE Applying edfapay.gradle to ${project.rootProject.name}")
        project.rootProject.apply {
            val inputStream = javaClass.classLoader.getResourceAsStream("edfapay.gradle")
            if (inputStream != null) {
                val tempFile = File.createTempFile("edfapay", ".gradle")
                tempFile.writeBytes(inputStream.readAllBytes())
                project.apply(mapOf("from" to tempFile))
                tempFile.deleteOnExit()
                logger("$MODULE Applied gradle file from: ${tempFile.absolutePath}")
            }else{
                logger("$MODULE Failed to apply edfapay repository from gradle file")
            }
        }
        // */


        // /*
        /* Applying via plugin itself */
        logger("$MODULE Adding edfapay repository to project")
        project.rootProject.allprojects{
            it.repositories.apply {
                logger("$MODULE   - ${it.name}")

                maven { repository ->
                    repository.url = URI("https://build.edfapay.com/nexus/content/repositories/edfapay-mobile/")
                    repository.isAllowInsecureProtocol = true
                    repository.credentials { credentials ->
                        credentials.username = username as String
                        credentials.password = password as String
                    }
                }
            }
        }
        // */
    }
}

private fun maskPassword(text: String, visibleStart: Int = 1, visibleEnd: Int = 1): String {
    if (text.length <= visibleStart + visibleEnd) return "*".repeat(text.length)

    val start = text.take(visibleStart)
    val end = text.takeLast(visibleEnd)
    val masked = "*".repeat(text.length - visibleStart - visibleEnd)
    return start + masked + end
}

