/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package tools

import org.gradle.api.Plugin
import org.gradle.api.initialization.Settings
import org.gradle.api.initialization.resolve.RepositoriesMode
import org.gradle.api.tasks.TaskExecutionException
import java.net.URI


/**
 * A simple 'hello world' plugin.
 */

private const val TAG = "[EdfapayPlugin]"

class Settings: Plugin<Settings> {
    val MODULE="$TAG[settings.gradle]"
    override fun apply(settings: Settings) {

        settings.gradle.settingsEvaluated {

            println("$MODULE Begins")

            val rMode = settings.dependencyResolutionManagement.repositoriesMode.orNull
            println("$MODULE RepositoriesMode:$rMode")
            if(rMode == RepositoriesMode.PREFER_PROJECT){
                println("$MODULE Ignore adding edfapay repository at 'dependencyResolutionManagement' in settings.gradle level")
                println("$MODULE   - It will be added at build.gradle level")
                return@settingsEvaluated
            }

            settings.gradle.rootProject {
                it.extensions.extraProperties.set("repositoriesMode", rMode!!.name)
            }


            println("$MODULE Adding edfapay repository to 'dependencyResolutionManagement' in settings.gradle")

            val username = settings.providers.gradleProperty("PARTNER_REPO_USERNAME").orNull
                ?: System.getenv().get("PARTNER_REPO_USERNAME")
                ?: throw TaskExecutionException(null, Errors.missingPartnerRepoUsername)

            val password = settings.providers.gradleProperty("PARTNER_REPO_PASSWORD").orNull
                ?: System.getenv().get("PARTNER_REPO_USERNAME")
                ?: throw TaskExecutionException(null, Errors.missingPartnerRepoUserPassword)

            println("$MODULE username:$username")
            println("$MODULE password:${maskPassword(password)}")

            // Add repositories to all projects
            settings.dependencyResolutionManagement.repositories.apply {
                maven { repository ->
                    repository.url = URI("https://build.edfapay.com/nexus/content/repositories/edfapay-mobile/")
                    repository.isAllowInsecureProtocol = true
                    repository.credentials { credentials ->
                        credentials.username = username
                        credentials.password = password
                    }
                }

                maven { repository ->
                    repository.url = URI("https://jitpack.io")
                }

                maven { repository ->
                    repository.url = URI("https://jitpack.io")
                    repository.credentials.username = "jp_dtett6nt05eqiekvc4hp4og128"
                }
            }


        }
    }

}

private fun maskPassword(text: String, visibleStart: Int = 1, visibleEnd: Int = 1): String {
    if (text.length <= visibleStart + visibleEnd) return "*".repeat(text.length)

    val start = text.take(visibleStart)
    val end = text.takeLast(visibleEnd)
    val masked = "*".repeat(text.length - visibleStart - visibleEnd)
    return start + masked + end
}

